-- MySQL Script generated by MySQL Workbench
-- Пн 25 июл 2022 18:21:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL,
  `firstname` VARCHAR(50) NULL,
  `lastname` VARCHAR(50) NULL,
  `phone` VARCHAR(15) NULL,
  `rating` FLOAT NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Пользователи сервиса Такси';


-- -----------------------------------------------------
-- Table `mydb`.`drivers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`drivers` (
  `id` INT NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `phone` VARCHAR(15) NULL,
  `rating` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Водители сервиса такси';


-- -----------------------------------------------------
-- Table `mydb`.`cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cars` (
  `id` INT NOT NULL,
  `brand` VARCHAR(20) NULL,
  `model` VARCHAR(20) NULL,
  `color` VARCHAR(15) NULL,
  `number` VARCHAR(15) NULL COMMENT 'Гос.номер машины',
  `status` ENUM('free', 'busy') NULL COMMENT 'Статус машины',
  `owner` INT NULL COMMENT 'Владелец машины',
  `class` ENUM('economy', 'comfort', 'comfort+', 'business') NULL COMMENT 'Класс машины',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Машины в такси';


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `id` INT NOT NULL,
  `time_order` DATETIME NULL,
  `location` VARCHAR(100) NULL COMMENT 'Адрес отправления',
  `destination` VARCHAR(100) NULL COMMENT 'Пункт назначения',
  `tarif` ENUM('economy', 'comfort', 'comfort+', 'business') NULL,
  `paymethod` ENUM('cash', 'card') NULL,
  `grade` INT UNSIGNED NULL,
  `price` INT UNSIGNED NULL COMMENT 'Стоимость',
  `distance` INT UNSIGNED NULL COMMENT 'Расстояние',
  `comment` VARCHAR(200) NULL COMMENT 'Комментарий к заказу',
  `users_id` INT NOT NULL,
  `cars_id` INT NOT NULL,
  `drivers_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `cars_id`, `drivers_id`),
  INDEX `fk_orders_users_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_orders_cars1_idx` (`cars_id` ASC) VISIBLE,
  INDEX `fk_orders_drivers1_idx` (`drivers_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_cars1`
    FOREIGN KEY (`cars_id`)
    REFERENCES `mydb`.`cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_drivers1`
    FOREIGN KEY (`drivers_id`)
    REFERENCES `mydb`.`drivers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Заказы такси';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
